FROM node:14.19.3 as build

WORKDIR /usr/src/app


FROM nginx:latest

# Overwrite our configuration file to default one
COPY ./default.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# COPY ./frontend/build /usr/share/nginx/html/